---
settings: 
  parallel: true

driver: vagrant

provisioner: 
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-6.4
- name: ubuntu-12.04

suites:
- name: release
  run_list:
    - recipe[etcd]
    - recipe[etcd_testing_setup]

- name: custom
  run_list:
    - recipe[etcd::compile_time]
    - recipe[etcd_testing_setup]
  attributes: {
    etcd: {
      url: "https://dl.dropboxusercontent.com/u/848501/etcd-130907.tar.gz",
      sha256: "6867fc7b6a53d60d93f2c53c3a06d4f5d8143ad06ca26a76b8d5b4d830248c2d",
      args: "-f -s 127.0.0.1:4001 -c 127.0.0.1:7001",
      version: "130812"
    }
  }

- name: compiletime
  run_list:
    - recipe[curl]
    - recipe[etcd::compile_time]

- name: cluster
  run_list:
    - recipe[curl]
    - recipe[etcd]
  attributes: {
    etcd: {
      seed_node: "#{node.name}"
    }
  }

