driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
    run_list: apt::default
  - name: debian-8
    run_list: apt::default
  - name: debian-9
    run_list: apt::default
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: service-docker
    run_list:
      - recipe[etcd_test::service_docker]
  - name: service-docker-multi
    run_list:
      - recipe[etcd_test::service_docker_multi]
  - name: service-systemd
    includes: [
      'debian-8',
      'debian-9',
      'centos-7',
      'fedora-26',
      'ubuntu-16.04',
      opensuse-leap-42
      ]
    run_list:
      - recipe[etcd_test::service_systemd]

  - name: service-systemd-multi
    includes: [
      'debian-8',
      'debian-9',
      'centos-7',
      'fedora-26',
      'ubuntu-16.04',
      opensuse-leap-42
      ]
    run_list:
      - recipe[etcd_test::service_systemd_multi]

  - name: service-upstart
    includes: [
      'ubuntu-14.04'
      ]
    run_list:
      - recipe[etcd_test::service_upstart]

  - name: service-upstart-multi
    includes: [
      'ubuntu-14.04'
      ]
    run_list:
      - recipe[etcd_test::service_upstart_multi]

  - name: service-sysvinit
    includes: [
      'debian-7',
      'centos-6'
      ]
    run_list:
      - recipe[etcd_test::service_sysvinit]

  - name: service-sysvinit-multi
    includes: [
      'debian-7',
      'centos-6'
      ]
    run_list:
      - recipe[etcd_test::service_sysvinit_multi]

  - name: keys
    includes: [
      'centos-7'
      ]
    run_list:
      - recipe[etcd_test::keys]

  - name: auto
    run_list:
      - recipe[etcd_test::auto]
